/* [ldio] generated by https://loading.io/ */
import React from 'react';

const LoadingBubbles = () => {
  return (
    <div className="flex w-full items-center">
      <svg style={{ width: 100, height: 100, margin: 'auto' }}>
        <circle cx="84" cy="50" r="10" fill="#700042">
          <animate
            attributeName="r"
            repeatCount="indefinite"
            dur="0.8333333333333334s"
            calcMode="spline"
            keyTimes="0;1"
            values="10;0"
            keySplines="0 0.5 0.5 1"
            begin="0s"
          ></animate>
          <animate
            attributeName="fill"
            repeatCount="indefinite"
            dur="3.3333333333333335s"
            calcMode="discrete"
            keyTimes="0;0.25;0.5;0.75;1"
            values="#700042;#dcdcdc;#f74371;#e30613;#700042"
            begin="0s"
          ></animate>
        </circle>
        <circle cx="16" cy="50" r="10" fill="#700042">
          <animate
            attributeName="r"
            repeatCount="indefinite"
            dur="3.3333333333333335s"
            calcMode="spline"
            keyTimes="0;0.25;0.5;0.75;1"
            values="0;0;10;10;10"
            keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
            begin="0s"
          ></animate>
          <animate
            attributeName="cx"
            repeatCount="indefinite"
            dur="3.3333333333333335s"
            calcMode="spline"
            keyTimes="0;0.25;0.5;0.75;1"
            values="16;16;16;50;84"
            keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
            begin="0s"
          ></animate>
        </circle>
        <circle cx="50" cy="50" r="10" fill="#e30613">
          <animate
            attributeName="r"
            repeatCount="indefinite"
            dur="3.3333333333333335s"
            calcMode="spline"
            keyTimes="0;0.25;0.5;0.75;1"
            values="0;0;10;10;10"
            keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
            begin="-0.8333333333333334s"
          ></animate>
          <animate
            attributeName="cx"
            repeatCount="indefinite"
            dur="3.3333333333333335s"
            calcMode="spline"
            keyTimes="0;0.25;0.5;0.75;1"
            values="16;16;16;50;84"
            keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
            begin="-0.8333333333333334s"
          ></animate>
        </circle>
        <circle cx="84" cy="50" r="10" fill="#f74371">
          <animate
            attributeName="r"
            repeatCount="indefinite"
            dur="3.3333333333333335s"
            calcMode="spline"
            keyTimes="0;0.25;0.5;0.75;1"
            values="0;0;10;10;10"
            keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
            begin="-1.6666666666666667s"
          ></animate>
          <animate
            attributeName="cx"
            repeatCount="indefinite"
            dur="3.3333333333333335s"
            calcMode="spline"
            keyTimes="0;0.25;0.5;0.75;1"
            values="16;16;16;50;84"
            keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
            begin="-1.6666666666666667s"
          ></animate>
        </circle>
        <circle cx="16" cy="50" r="10" fill="#dcdcdc">
          <animate
            attributeName="r"
            repeatCount="indefinite"
            dur="3.3333333333333335s"
            calcMode="spline"
            keyTimes="0;0.25;0.5;0.75;1"
            values="0;0;10;10;10"
            keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
            begin="-2.5s"
          ></animate>
          <animate
            attributeName="cx"
            repeatCount="indefinite"
            dur="3.3333333333333335s"
            calcMode="spline"
            keyTimes="0;0.25;0.5;0.75;1"
            values="16;16;16;50;84"
            keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
            begin="-2.5s"
          ></animate>
        </circle>
      </svg>
    </div>
  );
};

export default LoadingBubbles;
